# Generated by Django 6.0.1 on 2026-01-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='artista',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='musica',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='musica',
            name='nome',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='musica',
            index=models.Index(fields=['artista'], name='musicas_mus_artista_b4b729_idx'),
        ),
        migrations.AddIndex(
            model_name='musica',
            index=models.Index(fields=['nome'], name='musicas_mus_nome_8f953b_idx'),
        ),
    ]
