# Generated by Django 6.0.1 on 2026-01-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0002_alter_musica_artista_alter_musica_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='musica',
            name='musicas_mus_artista_b4b729_idx',
        ),
        migrations.RemoveIndex(
            model_name='musica',
            name='musicas_mus_nome_8f953b_idx',
        ),
    ]
