# Generated by Django 6.0.1 on 2026-01-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0003_remove_musica_musicas_mus_artista_b4b729_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='codigo',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
