# Generated by Django 6.0.1 on 2026-01-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0004_alter_musica_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='caminho_video',
            field=models.FileField(blank=True, help_text='Arquivo de vídeo associado à música', null=True, upload_to='K:\\Musicas\\karaoke'),
        ),
    ]
